## DATA TYPES 
This notebook looks at the data types of the NY taxi CSV files for the date range that we are using in the DataTalks class. 

Yellow and Green 2021 will also be included for the purpose of the BigQuery ML model.

In [2]:
import pandas as pd
import numpy as np  
import os 
from io import BytesIO
import requests
import utils

In [3]:
services = ['fhv','green','yellow']
init_url = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/'

In [4]:
dtypes_green_2019 = utils.get_service_year_dtypes(services[1], 2019)

In [5]:
dtypes_green_2019

,01_2019,02_2019,03_2019,04_2019,05_2019,06_2019,07_2019,08_2019,09_2019,10_2019,11_2019,12_2019
Column Name,,,,,,,,,,,,
VendorID,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
lpep_pickup_datetime,{str},{str},{str},{str},{str},{str},{str},{str},{str},{str},{str},{str}
lpep_dropoff_datetime,{str},{str},{str},{str},{str},{str},{str},{str},{str},{str},{str},{str}
store_and_fwd_flag,{str},{str},{str},{str},{str},{str},"{str, float}","{str, float}","{str, float}","{str, float}","{str, float}","{str, float}"
RatecodeID,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
PULocationID,{int},{int},{int},{int},{int},{int},{int},{int},{int},{int},{int},{int}
DOLocationID,{int},{int},{int},{int},{int},{int},{int},{int},{int},{int},{int},{int}
passenger_count,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
trip_distance,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
fare_amount,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
extra,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
mta_tax,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
tip_amount,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
tolls_amount,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
ehail_fee,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
improvement_surcharge,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
total_amount,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
payment_type,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
trip_type,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
congestion_surcharge,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}

In [5]:
dtypes_green_2020 = utils.get_service_year_dtypes(services[1], 2020)

,Data Types,Data Types,Data Types,Data Types,Data Types,Data Types,Data Types,Data Types,Data Types,Data Types,Data Types,Data Types
Column Name,,,,,,,,,,,,
VendorID,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
lpep_pickup_datetime,{str},{str},{str},{str},{str},{str},{str},{str},{str},{str},{str},{str}
lpep_dropoff_datetime,{str},{str},{str},{str},{str},{str},{str},{str},{str},{str},{str},{str}
store_and_fwd_flag,{str},{str},{str},{str},{str},{str},"{float, str}","{float, str}","{float, str}","{float, str}","{float, str}","{float, str}"
RatecodeID,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
PULocationID,{int},{int},{int},{int},{int},{int},{int},{int},{int},{int},{int},{int}
DOLocationID,{int},{int},{int},{int},{int},{int},{int},{int},{int},{int},{int},{int}
passenger_count,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
trip_distance,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
fare_amount,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
extra,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
mta_tax,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
tip_amount,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
tolls_amount,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
ehail_fee,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
improvement_surcharge,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
total_amount,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}
payment_type,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
trip_type,{int},{int},{int},{int},{int},{int},{float},{float},{float},{float},{float},{float}
congestion_surcharge,{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float},{float}

In [ ]:
dtypes = df_csv.dtypes
#print(dtypes)
print(dtypes[dtypes == 'object'])
print('RatecodeID: ', dtypes['RatecodeID'])

In [ ]:
col_name = f'{month}_{year}'
dtype_df = pd.DataFrame({col_name: dtypes})
dtype_df

In [ ]:
# GET yellow DF 
yellow_file_name = f"yellow_tripdata_{year}-{month}.csv.gz"

yellow_url = f"{init_url}yellow/{yellow_file_name}"
print(yellow_url)


yellow_r = requests.get(yellow_url)    
yellow_df = pd.read_csv(BytesIO(yellow_r.content), compression='gzip')
print(yellow_df.shape)

In [ ]:
# GET GREEN DF 
green_file_name = f"green_tripdata_{year}-{month}.csv.gz"

green_url = f"{init_url}green/{green_file_name}"
print(green_url)


green_r = requests.get(green_url)    
green_df = pd.read_csv(BytesIO(green_r.content), compression='gzip')
print(green_df.shape)

In [ ]:
# GET fhv DF 
fhv_file_name = f"fhv_tripdata_{year}-{month}.csv.gz"

fhv_url = f"{init_url}fhv/{fhv_file_name}"
print(fhv_url)


fhv_r = requests.get(fhv_url)    
fhv_df = pd.read_csv(BytesIO(fhv_r.content), compression='gzip')
print(fhv_df.shape)

In [ ]:
print(green_df.columns)

In [ ]:
df_yellow = df_csv.copy()

In [ ]:
print(green_df.columns)

In [ ]:
df_yellow.info()

In [ ]:
df_green.info()

In [ ]:
df_fhv.info()

In [ ]:
df_yellow.columns = df_yellow.columns.str.lower()
df_green.columns = df_green.columns.str.lower()
df_fhv.columns = df_fhv.columns.str.lower()

In [ ]:
# VendorID is an INT 
print('yellow',df_yellow.vendorid.value_counts())
print('green',df_green.vendorid.value_counts())

In [ ]:
# VendorID is an INT 
print('yellow',df_yellow.store_and_fwd_flag.value_counts())
print('green',df_green.store_and_fwd_flag.value_counts())

In [ ]:
# Passenger count is an INT 
print('yellow',df_yellow.passenger_count.value_counts())
print('green',df_green.passenger_count.value_counts())

In [ ]:
url = f'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year}-{month}.parquet'
r = requests.get(url)
df_parquet = pd.read_parquet(BytesIO(r.content))

In [ ]:
df_parquet.columns = df_parquet.columns.str.lower()
source_dtypes = df_parquet.dtypes
source_dtypes.drop(source_dtypes.index[-1], inplace=True)
series_string = source_dtypes.to_string()
print(series_string)

In [ ]:
0   VendorID               int64  
 1   tpep_pickup_datetime   object 
 2   tpep_dropoff_datetime  object 
 3   passenger_count        int64  
 4   trip_distance          float64
 5   RatecodeID             int64  
 6   store_and_fwd_flag     object 
 7   PULocationID           int64  
 8   DOLocationID           int64  
 9   payment_type           int64  
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64

In [ ]:
df_yellow = df_yellow.astype(source_dtypes)

In [ ]:
df_yellow.info()

In [ ]:
df_parquet.head()